/**
 * Types related to user activity and notification system.
 *
 * Metadata shapes match the JSONB constructed by database triggers in:
 *   - 20250529_add_activity_tables.sql  (record_submission_activity)
 *   - 20250522_toilet_submissions.sql   (process_approved_submission)
 */

import type {
  ToiletSubmissionType,
  ToiletSubmissionStatus,
} from "./contribution";

// ---------------------------------------------------------------------------
// Activity types
// ---------------------------------------------------------------------------

/**
 * All possible activity_type values.
 * Generated by the trigger: 'toilet_' || submission_type
 */
export type ActivityType = "toilet_new" | "toilet_edit" | "toilet_report";

/**
 * Metadata attached to a user activity record.
 * Shape matches the jsonb_build_object in record_submission_activity().
 */
export interface ActivityMetadata {
  submission_id?: string;
  submission_type?: ToiletSubmissionType;
  data?: {
    name?: string;
    status?: ToiletSubmissionStatus;
  };
}

/**
 * User activity record from the user_activity table.
 */
export interface UserActivity {
  id: string;
  activity_type: ActivityType;
  entity_id: string;
  metadata: ActivityMetadata;
  created_at: string;
}

// ---------------------------------------------------------------------------
// Notification types
// ---------------------------------------------------------------------------

/**
 * All possible notification_type values.
 * Set by process_approved_submission trigger.
 */
export type NotificationType = "submission_approved" | "submission_rejected";

/**
 * Metadata attached to a user notification record.
 * Shape matches the jsonb_build_object in process_approved_submission().
 */
export interface NotificationMetadata {
  submission_id?: string;
  toilet_id?: string;
}

/**
 * User notification record from the user_notifications table.
 */
export interface UserNotification {
  id: string;
  notification_type: NotificationType;
  title: string;
  message: string;
  entity_type?: string;
  entity_id?: string;
  metadata: NotificationMetadata;
  is_read: boolean;
  created_at: string;
}
